import type { Artifact } from "@/lib/types";

export const artifacts: Artifact[] = [
  {
    id: "art_report_xlsx",
    name: "report.xlsx",
    kind: "spreadsheet",
    sizeBytes: 254_003,
    createdAt: "2026-09-12T17:41:24Z",
    createdBy: "Weekly Operations Report",
    taskId: "task_ops_report",
    verification: "PASSED",
    workspaceId: "ws_operations",
  },
  {
    id: "art_ops_summary_pdf",
    name: "operations-summary.pdf",
    kind: "document",
    sizeBytes: 118_442,
    createdAt: "2026-09-12T17:40:02Z",
    createdBy: "Weekly Operations Report",
    taskId: "task_ops_report",
    verification: "PASSED",
    workspaceId: "ws_operations",
  },
  {
    id: "art_invoice_recon_xlsx",
    name: "invoice-reconciliation.xlsx",
    kind: "spreadsheet",
    sizeBytes: 402_881,
    createdAt: "2026-09-12T16:23:44Z",
    createdBy: "Invoice Reconciliation",
    taskId: "task_invoice",
    verification: "PASSED",
    workspaceId: "ws_finance",
  },
  {
    id: "art_qa_log",
    name: "repository-qa.log",
    kind: "log",
    sizeBytes: 61_233,
    createdAt: "2026-09-11T11:02:10Z",
    createdBy: "Repository QA",
    taskId: "task_repo_qa",
    verification: "FAILED",
    workspaceId: "ws_engineering",
  },
  {
    id: "art_exec_brief_pptx",
    name: "executive-briefing.pptx",
    kind: "presentation",
    sizeBytes: 1_284_120,
    createdAt: "2026-09-10T15:31:00Z",
    createdBy: "Executive Briefing",
    verification: "PASSED",
    workspaceId: "ws_operations",
  },
  {
    id: "art_monthly_data_xlsx",
    name: "monthly-analysis.xlsx",
    kind: "spreadsheet",
    sizeBytes: 512_009,
    createdAt: "2026-09-09T10:12:00Z",
    createdBy: "Monthly Data Analysis",
    verification: "PASSED",
    workspaceId: "ws_engineering",
  },
  {
    id: "art_compliance_pdf",
    name: "compliance-package.pdf",
    kind: "document",
    sizeBytes: 984_221,
    createdAt: "2026-09-08T09:44:00Z",
    createdBy: "Compliance Package",
    verification: "PASSED",
    workspaceId: "ws_finance",
  },
  {
    id: "art_pipeline_csv",
    name: "sales-pipeline.csv",
    kind: "report",
    sizeBytes: 88_120,
    createdAt: "2026-09-07T14:20:00Z",
    createdBy: "Sales Pipeline Cleanup",
    verification: "PASSED",
    workspaceId: "ws_operations",
  },
  {
    id: "art_research_md",
    name: "research-summary.md",
    kind: "document",
    sizeBytes: 24_880,
    createdAt: "2026-09-06T16:02:00Z",
    createdBy: "Research Summary",
    verification: "PASSED",
    workspaceId: "ws_engineering",
  },
  {
    id: "art_procurement_pdf",
    name: "procurement-review.pdf",
    kind: "report",
    sizeBytes: 341_552,
    createdAt: "2026-09-05T13:15:00Z",
    createdBy: "Procurement Review",
    verification: "PASSED",
    workspaceId: "ws_finance",
  },
  {
    id: "art_customer_report_pdf",
    name: "customer-report.pdf",
    kind: "report",
    sizeBytes: 204_775,
    createdAt: "2026-09-04T11:50:00Z",
    createdBy: "Customer Report",
    verification: "PASSED",
    workspaceId: "ws_operations",
  },
  {
    id: "art_diff_patch",
    name: "release-checks.patch",
    kind: "code",
    sizeBytes: 12_004,
    createdAt: "2026-09-03T18:00:00Z",
    createdBy: "Repository QA",
    verification: "PENDING",
    workspaceId: "ws_engineering",
  },
];

export function getArtifact(id: string): Artifact | undefined {
  return artifacts.find((a) => a.id === id);
}
