import type { KnowledgeSource } from "@/lib/types";

export const knowledgeSources: KnowledgeSource[] = [
  {
    id: "kn_ops_handbook",
    title: "Operations Handbook",
    type: "handbook",
    workspaceId: "ws_operations",
    access: "organization",
    version: "2026.3",
    provenance: "Operations Team",
    updatedAt: "2026-09-01T09:00:00Z",
    summary: "Standard operating procedures for weekly and monthly operations workflows.",
    sizeBytes: 2_204_881,
  },
  {
    id: "kn_reporting_policy",
    title: "Reporting Policy",
    type: "policy",
    workspaceId: "ws_operations",
    access: "organization",
    version: "4.1",
    provenance: "Compliance Office",
    updatedAt: "2026-08-22T09:00:00Z",
    summary: "Rules governing what may be included in operational and financial reports.",
    sizeBytes: 412_009,
  },
  {
    id: "kn_finance_sop",
    title: "Finance SOP",
    type: "sop",
    workspaceId: "ws_finance",
    access: "restricted",
    version: "7.0",
    provenance: "Finance Team",
    updatedAt: "2026-09-05T09:00:00Z",
    summary: "Standard operating procedures for invoice processing and reconciliation.",
    sizeBytes: 1_009_442,
  },
  {
    id: "kn_sales_procedure",
    title: "Sales Procedure",
    type: "procedure",
    workspaceId: "ws_operations",
    access: "workspace",
    version: "2.3",
    provenance: "Revenue Operations",
    updatedAt: "2026-07-18T09:00:00Z",
    summary: "Procedures for pipeline hygiene and sales reporting.",
    sizeBytes: 288_120,
  },
  {
    id: "kn_security_policy",
    title: "Security Policy",
    type: "policy",
    workspaceId: "ws_engineering",
    access: "organization",
    version: "9.2",
    provenance: "Security Office",
    updatedAt: "2026-09-10T09:00:00Z",
    summary: "Baseline security controls and handling requirements for sensitive data.",
    sizeBytes: 640_331,
  },
  {
    id: "kn_procurement_guide",
    title: "Procurement Guide",
    type: "guide",
    workspaceId: "ws_finance",
    access: "workspace",
    version: "1.4",
    provenance: "Procurement Team",
    updatedAt: "2026-06-30T09:00:00Z",
    summary: "Guidance for reviewing and approving procurement requests.",
    sizeBytes: 522_004,
  },
  {
    id: "kn_release_runbook",
    title: "Release Runbook",
    type: "sop",
    workspaceId: "ws_engineering",
    access: "workspace",
    version: "3.0",
    provenance: "Engineering",
    updatedAt: "2026-09-08T09:00:00Z",
    summary: "Steps and gates required to verify and ship a release.",
    sizeBytes: 380_112,
  },
  {
    id: "kn_data_dictionary",
    title: "Data Dictionary",
    type: "guide",
    workspaceId: "ws_engineering",
    access: "organization",
    version: "5.6",
    provenance: "Data Platform",
    updatedAt: "2026-08-14T09:00:00Z",
    summary: "Definitions for metrics and datasets used across analysis workflows.",
    sizeBytes: 1_540_223,
  },
  {
    id: "kn_comms_style",
    title: "Communications Style Guide",
    type: "guide",
    workspaceId: "ws_operations",
    access: "organization",
    version: "2.0",
    provenance: "Communications",
    updatedAt: "2026-05-11T09:00:00Z",
    summary: "Tone and formatting rules for internal and external communications.",
    sizeBytes: 210_884,
  },
  {
    id: "kn_compliance_matrix",
    title: "Compliance Matrix",
    type: "policy",
    workspaceId: "ws_finance",
    access: "restricted",
    version: "12.1",
    provenance: "Compliance Office",
    updatedAt: "2026-09-11T09:00:00Z",
    summary: "Mapping of controls to regulatory requirements for the compliance package.",
    sizeBytes: 902_441,
  },
];

export function getKnowledgeSource(id: string): KnowledgeSource | undefined {
  return knowledgeSources.find((k) => k.id === id);
}
