import type { Task, TaskStep } from "@/lib/types";

/** The flagship task — a 7-step branching workflow paused at approval. */
const opsReportSteps: TaskStep[] = [
  {
    id: "step_ops_1",
    index: 1,
    title: "Retrieve data",
    objective: "Retrieve approved operations data for the reporting period.",
    agentId: "agent_research",
    status: "COMPLETE",
    verification: "PASSED",
    dependsOn: [],
    tools: ["knowledge.search", "knowledge.cite"],
    expectedState: "3 authorized sources retrieved with provenance.",
    currentState: "Retrieved 3 authorized sources.",
    attempts: 1,
    maxAttempts: 3,
    startedAt: "2026-09-12T17:41:09Z",
    completedAt: "2026-09-12T17:41:13Z",
  },
  {
    id: "step_ops_2",
    index: 2,
    title: "Analyze data",
    objective: "Aggregate and validate the operational figures.",
    agentId: "agent_data",
    status: "COMPLETE",
    verification: "PASSED",
    dependsOn: ["step_ops_1"],
    tools: ["data.query", "data.validate", "data.aggregate"],
    expectedState: "Reconciled figures ready for reporting.",
    currentState: "Figures reconciled against source totals.",
    attempts: 1,
    maxAttempts: 3,
    startedAt: "2026-09-12T17:41:14Z",
    completedAt: "2026-09-12T17:41:17Z",
  },
  {
    id: "step_ops_3",
    index: 3,
    title: "Create report",
    objective: "Generate report.xlsx from the approved template.",
    agentId: "agent_spreadsheet",
    status: "RUNNING",
    verification: "PENDING",
    dependsOn: ["step_ops_2"],
    tools: ["spreadsheet.create", "spreadsheet.export"],
    expectedState: "report.xlsx generated matching the operations template.",
    currentState: "Generating report.xlsx…",
    attempts: 1,
    maxAttempts: 3,
    startedAt: "2026-09-12T17:41:18Z",
  },
  {
    id: "step_ops_4",
    index: 4,
    title: "Validate data",
    objective: "Independently reconcile totals in the generated report.",
    agentId: "agent_verification",
    status: "WAITING",
    verification: "NONE",
    dependsOn: ["step_ops_2"],
    tools: ["verify.reconcile", "verify.fields"],
    expectedState: "Report totals reconcile with source figures.",
    currentState: "Waiting for report.",
    attempts: 0,
    maxAttempts: 3,
  },
  {
    id: "step_ops_5",
    index: 5,
    title: "Prepare email",
    objective: "Draft an email to finance with the report attached.",
    agentId: "agent_communication",
    status: "WAITING",
    verification: "NONE",
    dependsOn: ["step_ops_3", "step_ops_4"],
    tools: ["email.draft"],
    expectedState: "Email drafted with verified report attached.",
    currentState: "Waiting.",
    attempts: 0,
    maxAttempts: 3,
  },
  {
    id: "step_ops_6",
    index: 6,
    title: "Approval",
    objective: "Request approval before any external communication.",
    agentId: "agent_communication",
    status: "WAITING",
    verification: "NONE",
    dependsOn: ["step_ops_5"],
    tools: [],
    expectedState: "Human approval recorded.",
    currentState: "Waiting.",
    attempts: 0,
    maxAttempts: 1,
    requiresApproval: true,
    approvalId: "appr_send_finance",
  },
  {
    id: "step_ops_7",
    index: 7,
    title: "Send",
    objective: "Send the approved email to finance.",
    agentId: "agent_communication",
    status: "WAITING",
    verification: "NONE",
    dependsOn: ["step_ops_6"],
    tools: ["email.send"],
    expectedState: "Email delivered to finance.",
    currentState: "Waiting.",
    attempts: 0,
    maxAttempts: 3,
  },
];

/** A task in active recovery on step 4. */
const repoQaSteps: TaskStep[] = [
  {
    id: "step_qa_1",
    index: 1,
    title: "Checkout repository",
    objective: "Prepare the repository at the target revision.",
    agentId: "agent_coding",
    status: "COMPLETE",
    verification: "PASSED",
    dependsOn: [],
    tools: ["code.edit"],
    expectedState: "Working tree ready.",
    currentState: "Checked out at HEAD.",
    attempts: 1,
    maxAttempts: 3,
    startedAt: "2026-09-11T10:58:00Z",
    completedAt: "2026-09-11T10:58:20Z",
  },
  {
    id: "step_qa_2",
    index: 2,
    title: "Run unit tests",
    objective: "Execute the unit test suite.",
    agentId: "agent_coding",
    status: "COMPLETE",
    verification: "PASSED",
    dependsOn: ["step_qa_1"],
    tools: ["code.test"],
    expectedState: "Unit suite green.",
    currentState: "412 passed.",
    attempts: 1,
    maxAttempts: 3,
    startedAt: "2026-09-11T10:58:21Z",
    completedAt: "2026-09-11T10:59:40Z",
  },
  {
    id: "step_qa_3",
    index: 3,
    title: "Run integration tests",
    objective: "Execute the integration suite.",
    agentId: "agent_coding",
    status: "COMPLETE",
    verification: "PASSED",
    dependsOn: ["step_qa_2"],
    tools: ["code.test"],
    expectedState: "Integration suite green.",
    currentState: "88 passed.",
    attempts: 1,
    maxAttempts: 3,
    startedAt: "2026-09-11T10:59:41Z",
    completedAt: "2026-09-11T11:01:30Z",
  },
  {
    id: "step_qa_4",
    index: 4,
    title: "Verify release checks",
    objective: "Confirm the release gate against the target environment.",
    agentId: "agent_verification",
    status: "RECOVERY",
    verification: "PENDING",
    dependsOn: ["step_qa_3"],
    tools: ["verify.artifact"],
    expectedState: "Release gate verified against target.",
    currentState: "The application state changed — re-checking the target.",
    attempts: 1,
    maxAttempts: 3,
    startedAt: "2026-09-11T11:01:31Z",
  },
];

function simpleSteps(
  prefix: string,
  agentId: string,
  titles: string[],
): TaskStep[] {
  return titles.map((title, i) => ({
    id: `${prefix}_${i + 1}`,
    index: i + 1,
    title,
    objective: `${title}.`,
    agentId,
    status: "COMPLETE",
    verification: "PASSED",
    dependsOn: i === 0 ? [] : [`${prefix}_${i}`],
    tools: [],
    expectedState: "Completed and verified.",
    currentState: "Completed.",
    attempts: 1,
    maxAttempts: 3,
  }));
}

export const tasks: Task[] = [
  {
    id: "task_ops_report",
    workspaceId: "ws_operations",
    name: "Weekly Operations Report",
    goal: "Prepare this week's operations report from approved data, attach it to an email for finance, and ask me before sending.",
    status: "AWAITING_APPROVAL",
    createdAt: "2026-09-12T17:41:04Z",
    updatedAt: "2026-09-12T17:41:27Z",
    executionId: "exec_1002",
    workflowId: "wf_weekly_ops",
    planVersion: "v3",
    assignedAgentId: "agent_planner",
    currentStepId: "step_ops_6",
    durationMs: 132_000,
    verification: "PASSED",
    steps: opsReportSteps,
    attachments: [{ id: "att_1", name: "operations-data.csv", size: 44_120 }],
    artifactIds: ["art_report_xlsx", "art_ops_summary_pdf"],
    approvalIds: ["appr_send_finance"],
  },
  {
    id: "task_invoice",
    workspaceId: "ws_finance",
    name: "Invoice Reconciliation",
    goal: "Reconcile last month's invoices against the ledger and flag any mismatches.",
    status: "COMPLETE",
    createdAt: "2026-09-12T16:20:00Z",
    updatedAt: "2026-09-12T16:27:08Z",
    executionId: "exec_1001",
    workflowId: "wf_invoice",
    planVersion: "v5",
    assignedAgentId: "agent_data",
    durationMs: 248_000,
    verification: "PASSED",
    steps: simpleSteps("step_inv", "agent_data", [
      "Load ledger",
      "Load invoices",
      "Reconcile entries",
      "Generate reconciliation",
    ]),
    attachments: [],
    artifactIds: ["art_invoice_recon_xlsx"],
    approvalIds: [],
  },
  {
    id: "task_repo_qa",
    workspaceId: "ws_engineering",
    name: "Repository QA",
    goal: "Run the full QA suite on the release branch and verify the release gate.",
    status: "RECOVERY",
    createdAt: "2026-09-11T10:57:40Z",
    updatedAt: "2026-09-11T11:02:10Z",
    executionId: "exec_1000",
    workflowId: "wf_repo_qa",
    planVersion: "v2",
    assignedAgentId: "agent_coding",
    currentStepId: "step_qa_4",
    durationMs: 271_000,
    verification: "PENDING",
    steps: repoQaSteps,
    attachments: [],
    artifactIds: ["art_qa_log", "art_diff_patch"],
    approvalIds: [],
  },
  {
    id: "task_research_summary",
    workspaceId: "ws_engineering",
    name: "Research Summary",
    goal: "Summarize this quarter's research notes into a shareable brief.",
    status: "AWAITING_APPROVAL",
    createdAt: "2026-09-12T15:02:00Z",
    updatedAt: "2026-09-12T15:12:00Z",
    executionId: "exec_0999",
    planVersion: "v1",
    assignedAgentId: "agent_research",
    currentStepId: "step_res_3",
    durationMs: 600_000,
    verification: "PASSED",
    steps: simpleSteps("step_res", "agent_research", [
      "Gather notes",
      "Synthesize brief",
      "Approval",
    ]),
    attachments: [],
    artifactIds: ["art_research_md"],
    approvalIds: ["appr_publish_update"],
  },
  {
    id: "task_procurement",
    workspaceId: "ws_finance",
    name: "Procurement Review",
    goal: "Review open procurement requests and prepare a summary for sign-off.",
    status: "RUNNING",
    createdAt: "2026-09-12T17:30:00Z",
    updatedAt: "2026-09-12T17:38:00Z",
    executionId: "exec_1003",
    planVersion: "v2",
    assignedAgentId: "agent_document",
    currentStepId: "step_proc_2",
    durationMs: 480_000,
    verification: "PENDING",
    steps: simpleSteps("step_proc", "agent_document", [
      "Collect requests",
      "Summarize",
      "Prepare sign-off",
    ]).map((s, i) =>
      i === 1
        ? { ...s, status: "RUNNING", verification: "PENDING", currentState: "Summarizing…" }
        : i === 2
          ? { ...s, status: "WAITING", verification: "NONE", currentState: "Waiting." }
          : s,
    ),
    attachments: [],
    artifactIds: ["art_procurement_pdf"],
    approvalIds: [],
  },
  {
    id: "task_monthly_data",
    workspaceId: "ws_engineering",
    name: "Monthly Data Analysis",
    goal: "Analyze last month's product metrics and highlight anomalies.",
    status: "COMPLETE",
    createdAt: "2026-09-09T09:50:00Z",
    updatedAt: "2026-09-09T10:12:00Z",
    executionId: "exec_0998",
    workflowId: "wf_monthly_data",
    planVersion: "v4",
    assignedAgentId: "agent_data",
    durationMs: 1_320_000,
    verification: "PASSED",
    steps: simpleSteps("step_mda", "agent_data", [
      "Load metrics",
      "Run analysis",
      "Flag anomalies",
      "Generate report",
    ]),
    attachments: [],
    artifactIds: ["art_monthly_data_xlsx"],
    approvalIds: [],
  },
  {
    id: "task_exec_brief",
    workspaceId: "ws_operations",
    name: "Executive Briefing",
    goal: "Turn the weekly figures into a short executive briefing deck.",
    status: "COMPLETE",
    createdAt: "2026-09-10T15:00:00Z",
    updatedAt: "2026-09-10T15:31:00Z",
    executionId: "exec_0997",
    planVersion: "v2",
    assignedAgentId: "agent_presentation",
    durationMs: 1_860_000,
    verification: "PASSED",
    steps: simpleSteps("step_eb", "agent_presentation", [
      "Gather figures",
      "Draft narrative",
      "Build deck",
    ]),
    attachments: [],
    artifactIds: ["art_exec_brief_pptx"],
    approvalIds: [],
  },
  {
    id: "task_pipeline_cleanup",
    workspaceId: "ws_operations",
    name: "Sales Pipeline Cleanup",
    goal: "Clean stale opportunities from the pipeline and export the result.",
    status: "FAILED",
    createdAt: "2026-09-07T14:00:00Z",
    updatedAt: "2026-09-07T14:20:00Z",
    executionId: "exec_0996",
    planVersion: "v1",
    assignedAgentId: "agent_data",
    durationMs: 300_000,
    verification: "FAILED",
    steps: simpleSteps("step_pipe", "agent_data", [
      "Load pipeline",
      "Identify stale entries",
      "Export result",
    ]).map((s, i) =>
      i === 2
        ? {
            ...s,
            status: "FAILED",
            verification: "FAILED",
            currentState: "The target could not be verified.",
          }
        : s,
    ),
    attachments: [],
    artifactIds: ["art_pipeline_csv"],
    approvalIds: [],
  },
  {
    id: "task_customer_report",
    workspaceId: "ws_operations",
    name: "Customer Report",
    goal: "Generate the monthly customer report for the operations team.",
    status: "COMPLETE",
    createdAt: "2026-09-04T11:20:00Z",
    updatedAt: "2026-09-04T11:50:00Z",
    executionId: "exec_0995",
    planVersion: "v3",
    assignedAgentId: "agent_document",
    durationMs: 1_800_000,
    verification: "PASSED",
    steps: simpleSteps("step_cust", "agent_document", [
      "Collect data",
      "Generate report",
      "Verify",
    ]),
    attachments: [],
    artifactIds: ["art_customer_report_pdf"],
    approvalIds: [],
  },
  {
    id: "task_compliance",
    workspaceId: "ws_finance",
    name: "Compliance Package",
    goal: "Assemble the quarterly compliance package from approved documents.",
    status: "QUEUED",
    createdAt: "2026-09-12T18:02:00Z",
    updatedAt: "2026-09-12T18:02:00Z",
    planVersion: "v1",
    durationMs: 0,
    verification: "NONE",
    steps: simpleSteps("step_comp", "agent_document", [
      "Collect documents",
      "Assemble package",
      "Verify",
    ]).map((s) => ({
      ...s,
      status: "WAITING",
      verification: "NONE",
      currentState: "Queued.",
    })),
    attachments: [],
    artifactIds: ["art_compliance_pdf"],
    approvalIds: [],
  },
];

export function getTask(id: string): Task | undefined {
  return tasks.find((t) => t.id === id);
}
