"""Real desktop-execution mission: generate content with the LLM, then take
control of the machine (open MS Word / browser) to actually perform the task.

This is the honest "end-to-end, live, takes control of the laptop" path used by
goals like "write a paragraph on tree in ms word" or "search youtube for X".

Design + honesty:
* Content (e.g. the paragraph) is generated by the REAL model router when a
  provider is configured; falls back to a deterministic local draft otherwise.
* The side effect is REAL: it drives MS Word via win32com (COM automation) —
  opening Word visibly, typing the content, and saving a real .docx. If Word /
  pywin32 is unavailable it writes a real .docx via python-docx, or a real .txt
  as a last resort — never a fake success.
* Independent verification reopens the produced file and confirms the content
  actually landed before the mission is reported complete.
* All file output is confined to a configurable output directory.
"""

from __future__ import annotations

import os
import re
from dataclasses import dataclass, field
from pathlib import Path


# --------------------------------------------------------------------------
# Intent detection — is this a desktop-control goal? (heuristic, not hardcoded
# to one phrase; the orchestrator/LLM still plans, this only routes execution)
# --------------------------------------------------------------------------

_WORD_HINTS = ("ms word", "microsoft word", "in word", "word document", "a document", ".docx")
_NOTEPAD_HINTS = ("notepad", "note pad", ".txt", "text file", "in a text", "text document")
_WRITE_HINTS = ("write", "draft", "compose", "paragraph", "essay", "note", "letter", "report")
_BROWSER_HINTS = ("youtube", "search", "google", "open website", "browse", "open browser")
_EMAIL_HINTS = ("email", "e-mail", "mail ", "send mail", "send an email", "send a mail")

# Reassign-work intent: someone is absent and their work must be handed to a
# colleague. Detection also requires an uploaded roster (.xlsx) — see
# detect_desktop_goal.
_REASSIGN_HINTS = (
    "won't come", "wont come", "will not come", "not coming", "not come",
    "is absent", "on leave", "off today", "reassign", "re-assign",
    "assign his work", "assign her work", "assign their work",
    "assign his tasks", "assign her tasks", "cover for", "cover his",
    "cover her", "whom to assign", "who to assign", "who should cover",
    "who can cover",
)

_EMAIL_RE = re.compile(r"[\w.+-]+@[\w-]+\.[\w.-]+")


@dataclass
class DesktopPlan:
    kind: str                 # "word_write" | "notepad_write" | "web_search" | "open_app" | "send_email" | "reassign_work"
    topic: str = ""
    query: str = ""
    app: str = ""
    filename: str = "autoflow_document.docx"
    recipient: str = ""
    subject: str = ""
    roster_path: str = ""     # uploaded .xlsx path (reassign_work)
    absent_query: str = ""    # raw goal text naming the absent person


def detect_desktop_goal(goal: str, *, roster_path: str = "") -> DesktopPlan | None:
    """Classify a goal into a supported real desktop action, or None.

    ``roster_path`` (optional) is the path to an uploaded employee spreadsheet.
    When present and the goal reads like an absence/reassignment, the goal is
    routed to the ``reassign_work`` flow (roster -> Gemini pick -> Gmail compose)
    instead of a plain email.
    """
    g = (goal or "").lower().strip()
    if not g:
        return None

    # Reassign-work intent (checked FIRST, and only when a roster .xlsx was
    # uploaded — otherwise fall through to the normal email/word/etc. routing so
    # nothing existing changes behaviour).
    if roster_path and str(roster_path).lower().endswith(".xlsx") \
            and any(h in g for h in _REASSIGN_HINTS):
        return DesktopPlan(kind="reassign_work", roster_path=str(roster_path),
                           absent_query=goal)

    # Email intent (checked before generic 'write'/'compose' so "compose an
    # email" routes to email, not Word).
    if any(h in g for h in _EMAIL_HINTS) or "@" in goal:
        m = _EMAIL_RE.search(goal)
        recipient = m.group(0) if m else ""
        topic = _extract_email_topic(goal)
        return DesktopPlan(kind="send_email", topic=topic, recipient=recipient,
                           subject=(topic[:80] or "Message from AutoFlow"))

    # Notepad intent (checked before Word so "in a text file / notepad" routes
    # to Notepad, not Word).
    if any(h in g for h in _NOTEPAD_HINTS):
        topic = _extract_topic(goal)
        slug = re.sub(r"[^a-z0-9]+", "_", topic.lower()).strip("_")[:40] or "note"
        return DesktopPlan(kind="notepad_write", topic=topic, filename=f"autoflow_{slug}.txt")

    is_word = any(h in g for h in _WORD_HINTS)
    is_write = any(h in g for h in _WRITE_HINTS)
    if is_word or (is_write and "word" in g):
        topic = _extract_topic(goal)
        fname = _filename_from_topic(topic)
        return DesktopPlan(kind="word_write", topic=topic, filename=fname)

    if any(h in g for h in _BROWSER_HINTS):
        return DesktopPlan(kind="web_search", query=goal)

    if g.startswith("open ") and not is_word:
        return DesktopPlan(kind="open_app", app=g[len("open "):].strip())

    return None


def _extract_email_topic(goal: str) -> str:
    """Pull the letter subject from an email goal.

    e.g. "write a apology letter and email to sushovan1908@gmail.com"
      -> "apology letter"
         "send an email to x@y.com about the weekly report"
      -> "the weekly report"
    """
    g = (goal or "").strip()
    # Prefer an explicit 'about/regarding' clause.
    m = re.search(r"\b(?:about|regarding|on)\s+(.+)", g, flags=re.IGNORECASE)
    if m:
        topic = m.group(1)
    else:
        # Drop the recipient clause and email address, keep the "what to write".
        topic = _EMAIL_RE.sub("", g)
        topic = re.sub(r"\b(?:and\s+)?(?:e-?mail|send|mail)\b.*", "", topic,
                       flags=re.IGNORECASE)
        topic = re.sub(r"^\s*(?:write|draft|compose|create)\s+(?:an?\s+)?", "",
                       topic, flags=re.IGNORECASE)
    topic = _EMAIL_RE.sub("", topic)
    topic = re.sub(r"\bto\b\s*$", "", topic, flags=re.IGNORECASE)
    return topic.strip(" .\t,") or "the requested message"


def _extract_topic(goal: str) -> str:
    """Pull the subject out of goals like:
      'write a paragraph on tree in ms word' -> 'tree'
      'Write TREE into a Notepad (.txt) document and open it' -> 'TREE'
    """
    g = goal.strip()
    # Prefer an explicit 'on/about/regarding X' clause.
    m = re.search(r"\b(?:on|about|regarding)\s+(.+)", g, flags=re.IGNORECASE)
    if m:
        topic = m.group(1)
    else:
        topic = g
        # Drop a leading verb phrase: "write a paragraph", "write", "create a note".
        topic = re.sub(
            r"^\s*(?:write|draft|compose|create|make|type|put)\s+"
            r"(?:an?\s+)?(?:paragraph|essay|note|letter|report|text|line|word)?\s*",
            "", topic, flags=re.IGNORECASE,
        )
        # Cut off the destination clause: "into/in a notepad/word/text file/document".
        topic = re.split(
            r"\b(?:in|into|on|as|to)\b\s+(?:an?\s+|the\s+)?"
            r"(?:ms\s+word|microsoft\s+word|word|notepad|note\s*pad|text\s*file|text\s*document|document|\.txt|\.docx)",
            topic, flags=re.IGNORECASE,
        )[0]
    # Remove any leftover destination words + trailing "and open it".
    topic = re.sub(r"\band\s+open\s+it\b.*$", "", topic, flags=re.IGNORECASE)
    topic = re.sub(r"\(\.?(?:txt|docx)\)", "", topic, flags=re.IGNORECASE)
    topic = re.sub(r"\b(?:ms\s+word|microsoft\s+word|word|notepad|note\s*pad|"
                   r"text\s*file|text\s*document|document)\b", "", topic, flags=re.IGNORECASE)
    return topic.strip(" .\t,()") or "the requested topic"


def _filename_from_topic(topic: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "_", topic.lower()).strip("_")[:40] or "document"
    return f"autoflow_{slug}.docx"


# --------------------------------------------------------------------------
# Content generation via the real LLM (fails closed to a deterministic draft)
# --------------------------------------------------------------------------


def generate_paragraph(topic: str, *, router=None) -> tuple[str, str]:
    """Return (text, source) where source is 'llm' or 'local'."""
    prompt = (
        f"Write a single well-formed, informative paragraph (4-6 sentences) about "
        f"{topic}. Return only the paragraph text with no preamble, title, or list."
    )
    if router is not None:
        try:
            from ..schemas.enums import ModelRole
            from ..schemas.models import ModelRequest

            req = ModelRequest(
                request_id="mreq_deskgen1",
                required_role=ModelRole.EXECUTOR,
                required_capabilities={"reasoning": True},
                max_output_tokens=400,
                temperature=0.4,
            )
            resp = router.generate(req, prompt)
            text = (resp.text or "").strip()
            if text:
                return text, ("llm" if not resp.is_fallback else "local")
        except Exception:  # noqa: BLE001 - never fail the mission on model error
            pass
    # Deterministic local draft (honest offline fallback — clearly generic).
    text = (
        f"{topic.capitalize()} is a subject worth summarizing clearly and "
        f"accurately. This paragraph was prepared by AutoFlow to demonstrate an "
        f"end-to-end run in which the system generates content and then operates "
        f"a real application to record it. The key points about {topic} are "
        f"organized into a concise, readable form suitable for a document. "
        f"AutoFlow verifies the result after writing it, so completion reflects a "
        f"real, checked outcome rather than an assumption."
    )
    return text, "local"


# --------------------------------------------------------------------------
# Real Word write (win32com) with honest fallbacks + independent verification
# --------------------------------------------------------------------------


@dataclass
class DesktopResult:
    kind: str
    executed: bool
    verified: bool
    outcome: str
    mode: str                 # LIVE_WORD | DOCX_FALLBACK | TXT_FALLBACK | BROWSER | APP | FAILED
    artifact_path: str | None = None
    content_preview: str = ""
    content_source: str = ""
    reason: str = ""
    steps: list[dict] = field(default_factory=list)


def _output_dir() -> Path:
    env = os.environ.get("AUTOFLOW_DESKTOP_OUTPUT") or os.environ.get("AUTOFLOW_NEEDLE_OUTPUT")
    d = Path(env) if env else (Path.home() / "Downloads")
    d.mkdir(parents=True, exist_ok=True)
    return d


def _verify_docx(path: Path, expected_snippet: str) -> bool:
    try:
        from ..documents.base import open_document
        text = open_document(path).read_text()
    except Exception:  # noqa: BLE001
        try:
            text = path.read_text(encoding="utf-8", errors="ignore")
        except Exception:  # noqa: BLE001
            return False
    snippet = (expected_snippet or "").strip()[:40]
    return bool(snippet) and snippet in text


def write_paragraph_in_word(
    content: str, filename: str, *, emit=None, visible: bool = True
) -> DesktopResult:
    """Open MS Word, type ``content``, save a real .docx, and verify it.

    Emits step callbacks (emit(stage, message)) for the live trace. Honest
    fallbacks: python-docx if Word COM is unavailable, then plain .txt.
    """
    steps: list[dict] = []

    def step(stage: str, message: str, ok: bool = True) -> None:
        steps.append({"stage": stage, "message": message, "ok": ok})
        if emit:
            emit(stage, message)

    target = _output_dir() / Path(filename).name

    # 1. Try real Word via COM. The document is LEFT OPEN and VISIBLE so the
    # user sees Word with the typed text and closes it themselves — we never
    # Quit/Close it. Verification reads the live open document's own content.
    try:
        import pythoncom  # type: ignore
        import win32com.client  # type: ignore

        step("computer", "launching Microsoft Word")
        pythoncom.CoInitialize()
        # DispatchEx spawns a fresh, independent Word process that keeps running
        # after this thread finishes (so the window stays open for the user).
        word = win32com.client.DispatchEx("Word.Application")
        word.Visible = True
        try:
            word.Activate()
        except Exception:  # noqa: BLE001 - Activate is best-effort
            pass
        step("document", "creating a new Word document")
        doc = word.Documents.Add()
        step("document", "typing the generated content into Word")
        doc.Content.Text = content
        step("document", f"saving the document as {target.name}")
        # 16 = wdFormatXMLDocument (.docx)
        doc.SaveAs(str(target), FileFormat=16)
        # Verify against the LIVE open document (do NOT close it).
        try:
            live_text = doc.Content.Text or ""
        except Exception:  # noqa: BLE001
            live_text = ""
        pythoncom.CoUninitialize()
        snippet = content.strip()[:40]
        verified = bool(snippet) and (snippet in live_text or _verify_docx(target, content))
        step("verify", "confirmed the text is present in the open Word document", verified)
        step("document", "leaving Microsoft Word open for you to review/close", True)
        return DesktopResult(
            kind="word_write", executed=True, verified=verified,
            outcome="complete" if verified else "not_verified",
            mode="LIVE_WORD", artifact_path=str(target),
            content_preview=content[:200], steps=steps,
            reason="" if verified else "written text not confirmed in the document",
        )
    except Exception as exc:  # noqa: BLE001 - Word/pywin32 unavailable -> fallback
        step("computer", f"MS Word not available ({type(exc).__name__}); using python-docx", ok=True)

    # 2. Fallback: real .docx via python-docx (still a real, verifiable artifact).
    try:
        import docx  # python-docx

        d = docx.Document()
        d.add_paragraph(content)
        d.save(str(target))
        verified = _verify_docx(target, content)
        step("verify", "reopened the .docx and confirmed the content", verified)
        return DesktopResult(
            kind="word_write", executed=True, verified=verified,
            outcome="complete" if verified else "not_verified",
            mode="DOCX_FALLBACK", artifact_path=str(target),
            content_preview=content[:200], steps=steps,
            reason="" if verified else "written file did not contain expected content",
        )
    except Exception as exc:  # noqa: BLE001
        step("document", f"python-docx unavailable ({type(exc).__name__}); writing .txt", ok=True)

    # 3. Last resort: real .txt.
    txt = target.with_suffix(".txt")
    try:
        txt.write_text(content, encoding="utf-8")
        verified = txt.exists() and content[:40] in txt.read_text(encoding="utf-8")
        step("verify", "confirmed the text file content", verified)
        return DesktopResult(
            kind="word_write", executed=True, verified=verified,
            outcome="complete" if verified else "not_verified",
            mode="TXT_FALLBACK", artifact_path=str(txt),
            content_preview=content[:200], steps=steps,
            reason="" if verified else "text file verification failed",
        )
    except Exception as exc:  # noqa: BLE001
        step("document", f"could not write output: {exc}", ok=False)
        return DesktopResult(
            kind="word_write", executed=False, verified=False, outcome="failed",
            mode="FAILED", steps=steps, reason=str(exc),
        )


def write_notepad(content: str, filename: str, *, emit=None) -> DesktopResult:
    """Write content to a real .txt file and open it in Notepad (stays open).

    Emits step callbacks for the live trace. Honest: the file is always written
    (real, verifiable), and Notepad is launched detached so it stays open for
    the user. Verification reopens the file and confirms the content.
    """
    import subprocess

    steps: list[dict] = []

    def step(stage: str, message: str, ok: bool = True) -> None:
        steps.append({"stage": stage, "message": message, "ok": ok})
        if emit:
            emit(stage, message)

    name = Path(filename).name or "note.txt"
    if not name.lower().endswith(".txt"):
        name = f"{name}.txt"
    target = _output_dir() / name

    step("document", f"writing the text file {target.name}")
    try:
        target.write_text(content, encoding="utf-8")
    except OSError as exc:
        step("document", f"could not write file: {exc}", False)
        return DesktopResult(kind="notepad_write", executed=False, verified=False,
                             outcome="failed", mode="FAILED", steps=steps, reason=str(exc))

    step("computer", "opening the file in Notepad")
    try:
        subprocess.Popen(["notepad.exe", str(target)])
        mode = "LIVE_NOTEPAD"
    except Exception as exc:  # noqa: BLE001 - notepad unavailable; file still written
        step("computer", f"Notepad could not launch ({type(exc).__name__}); file written", True)
        mode = "TXT_FALLBACK"

    # Verify by reopening the file and confirming the content landed.
    snippet = content.strip()[:40]
    try:
        written = target.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        written = ""
    verified = bool(snippet) and snippet in written
    step("verify", "confirmed the content in the text file", verified)
    if mode == "LIVE_NOTEPAD":
        step("document", "leaving Notepad open for you to review/close", True)
    return DesktopResult(
        kind="notepad_write", executed=True, verified=verified,
        outcome="complete" if verified else "not_verified",
        mode=mode, artifact_path=str(target), content_preview=content[:200],
        steps=steps, reason="" if verified else "written text not confirmed",
    )


def open_in_browser(url_or_query: str, *, is_search: bool, emit=None) -> DesktopResult:
    """Open a real browser to a URL or a search results page."""
    import urllib.parse
    import webbrowser

    steps: list[dict] = []

    def step(stage: str, message: str, ok: bool = True) -> None:
        steps.append({"stage": stage, "message": message, "ok": ok})
        if emit:
            emit(stage, message)

    if is_search:
        # Extract a query after 'search ... for' / 'youtube ...'
        q = re.sub(r".*\b(?:search(?:\s+for)?|youtube|google)\b", "", url_or_query,
                   flags=re.IGNORECASE).strip(" :\t") or url_or_query
        low = url_or_query.lower()
        if "youtube" in low:
            url = "https://www.youtube.com/results?search_query=" + urllib.parse.quote(q)
        else:
            url = "https://www.google.com/search?q=" + urllib.parse.quote(q)
        step("browser", f"opening browser search for '{q}'")
    else:
        url = url_or_query if url_or_query.startswith("http") else "https://" + url_or_query
        step("browser", f"opening {url}")

    try:
        webbrowser.open(url)
        step("verify", "browser open command issued", True)
        return DesktopResult(
            kind="web_search", executed=True, verified=True, outcome="complete",
            mode="BROWSER", artifact_path=url, content_preview=url, steps=steps,
        )
    except Exception as exc:  # noqa: BLE001
        step("browser", f"failed to open browser: {exc}", False)
        return DesktopResult(kind="web_search", executed=False, verified=False,
                             outcome="failed", mode="FAILED", steps=steps, reason=str(exc))


# --------------------------------------------------------------------------
# Real email send (SMTP) — generates a body with the LLM, sends via SMTP,
# and verifies the transport accepted it. Used for "send an email ..." goals.
# --------------------------------------------------------------------------


def _generate_email_body(topic: str, *, router=None) -> str:
    prompt = (
        f"Write a complete, polite email/letter about: {topic}. "
        f"Include a greeting line and a closing (e.g. 'Best regards,'). "
        f"Keep it 4-6 sentences. Return only the letter text — no subject line."
    )
    if router is not None:
        try:
            from ..schemas.enums import ModelRole
            from ..schemas.models import ModelRequest

            req = ModelRequest(
                request_id="mreq_email01",
                required_role=ModelRole.EXECUTOR,
                required_capabilities={"reasoning": True},
                max_output_tokens=400,
                temperature=0.5,
            )
            resp = router.generate(req, prompt)
            text = (resp.text or "").strip()
            if text:
                return text
        except Exception:  # noqa: BLE001
            pass
    return (
        f"Hello,\n\nI am writing regarding {topic}. Please consider this a sincere "
        f"note on the matter, and let me know if there is anything further I can "
        f"do.\n\nBest regards,"
    )


def _extract_subject(topic: str) -> str:
    """A short, human subject line from the goal topic."""
    t = (topic or "").strip()
    low = t.lower()
    if "apolog" in low:
        return "Apology"
    if "thank" in low:
        return "Thank you"
    if "invit" in low:
        return "Invitation"
    if "follow up" in low or "follow-up" in low:
        return "Following up"
    # Title-case the first few words as a fallback subject.
    words = t.split()
    return " ".join(words[:6]).strip(" .") or "Message"


def send_email_real(plan: "DesktopPlan", *, router=None, emit=None) -> DesktopResult:
    """Open Gmail compose in the browser with the letter pre-filled — the user
    reviews it in their own Gmail and clicks Send themselves.

    This is the honest "from my Gmail to a real address" flow: AutoFlow writes
    the letter (real LLM), opens Gmail's compose window pre-populated with the
    recipient, subject and body, and STOPS at the last step before send. No
    SMTP, no headless send — the human performs the actual send from their
    signed-in Gmail, so it truly goes from their account to the recipient.
    """
    import urllib.parse
    import webbrowser

    steps: list[dict] = []

    def step(stage: str, message: str, ok: bool = True) -> None:
        steps.append({"stage": stage, "message": message, "ok": ok})
        if emit:
            emit(stage, message)

    recipient = (plan.recipient or "").strip()
    if not recipient:
        step("gmail", "no recipient found in the request", False)
        return DesktopResult(kind="send_email", executed=False, verified=False,
                             outcome="failed", mode="FAILED", steps=steps,
                             reason="no recipient address in the goal")

    step("document", f"writing the letter for {recipient}")
    body = _generate_email_body(plan.topic or "your request", router=router)
    subject = _extract_subject(plan.topic or plan.subject or "Message")

    # Gmail compose URL with everything pre-filled. Opening this in the default
    # browser (where the user is signed into Gmail) pops the compose window with
    # the recipient/subject/body ready — the user reviews and hits Send.
    params = {"view": "cm", "fs": "1", "to": recipient, "su": subject, "body": body}
    url = "https://mail.google.com/mail/?" + urllib.parse.urlencode(params)

    step("gmail", "opening Gmail compose with the letter pre-filled")
    try:
        webbrowser.open(url)
    except Exception as exc:  # noqa: BLE001
        step("gmail", f"could not open the browser: {exc}", False)
        return DesktopResult(kind="send_email", executed=False, verified=False,
                             outcome="failed", mode="FAILED", steps=steps, reason=str(exc))

    step("approval", "Gmail is open with your draft — review it and click Send", True)
    return DesktopResult(
        kind="send_email", executed=True, verified=True, outcome="complete",
        mode="GMAIL_COMPOSE", artifact_path=recipient,
        content_preview=f"To: {recipient}\nSubject: {subject}\n\n{body[:200]}",
        steps=steps,
    )


# --------------------------------------------------------------------------
# Reassign-work flow: read an uploaded roster (.xlsx), pick the best colleague
# to cover an absent employee (Gemini, honest heuristic fallback), then open a
# work-assignment email in Gmail compose (reuses the same Gmail-compose path).
# --------------------------------------------------------------------------


def _reassign_email_body(absent, assignee, prediction: dict, *, router=None) -> str:
    """Compose the work-assignment letter for the chosen colleague."""
    absent_name = getattr(absent, "name", "") or "a teammate"
    assignee_name = getattr(assignee, "name", "") or (
        prediction.get("assignee_name") or "there")
    tasks = getattr(absent, "assigned_work", "") or "their in-progress work"
    reason = prediction.get("reason", "").strip()

    first = assignee_name.split()[0] if assignee_name else "there"
    lines = [
        f"Hi {first},",
        "",
        f"{absent_name} is out today, so we'd like you to cover their work for "
        f"the day. The tasks to pick up are: {tasks}.",
    ]
    if reason:
        lines += ["", f"You were chosen because {reason[0].lower() + reason[1:]}"
                  if reason and reason[0].isupper() else f"You were chosen because {reason}"]
    lines += [
        "",
        "Please let me know if you have any questions or need anything handed "
        "over. Thanks a lot for stepping in.",
        "",
        "Best regards,",
    ]
    return "\n".join(lines)


def run_reassign_work(plan: "DesktopPlan", *, router=None, emit=None) -> DesktopResult:
    """Read the roster, predict the best assignee, open a work-assignment email.

    Steps narrated for the live trace:
      1. extract the roster from the uploaded spreadsheet (real openpyxl read,
         surfaced as an extraction step),
      2. identify the absent person from the goal text,
      3. ask Gemini to pick the best colleague (honest heuristic fallback),
      4. open a work-assignment email in Gmail compose (reuses send path).
    """
    import urllib.parse
    import webbrowser

    from .employee_data import RosterError, find_absent, read_roster
    from .gemini_client import predict_assignee

    steps: list[dict] = []

    def step(stage: str, message: str, ok: bool = True) -> None:
        steps.append({"stage": stage, "message": message, "ok": ok})
        if emit:
            emit(stage, message)

    roster_path = (plan.roster_path or "").strip()
    step("computer", f"extracting the employee roster from {Path(roster_path).name}"
         if roster_path else "extracting the employee roster")
    try:
        roster = read_roster(roster_path)
    except RosterError as exc:
        step("computer", f"could not read the roster: {exc}", False)
        return DesktopResult(kind="reassign_work", executed=False, verified=False,
                             outcome="failed", mode="FAILED", steps=steps,
                             reason=str(exc))
    step("computer", f"extracted {len(roster)} employees from the roster")

    absent = find_absent(roster, plan.absent_query or "")
    if absent is None:
        step("planner", "could not identify the absent employee from the request",
             False)
        return DesktopResult(
            kind="reassign_work", executed=False, verified=False, outcome="failed",
            mode="FAILED", steps=steps,
            reason="could not match the absent employee's name against the roster")
    step("planner", f"absent employee identified: {absent.name}")

    step("research", f"analysing skills and workload to cover {absent.name}'s work")
    prediction = predict_assignee(absent, roster)
    assignee_email = (prediction.get("assignee_email") or "").strip()
    assignee_name = (prediction.get("assignee_name") or "").strip()
    source = prediction.get("source", "heuristic")

    if not assignee_email:
        step("planner", "no suitable colleague with a contact email was found",
             False)
        return DesktopResult(
            kind="reassign_work", executed=False, verified=False, outcome="failed",
            mode="FAILED", steps=steps,
            reason="no assignable colleague with an email address in the roster")

    via = "Gemini" if source == "gemini" else "skill/department match"
    step("planner", f"selected {assignee_name} ({assignee_email}) via {via}")

    # Resolve the assignee Employee object (for a richer email body).
    assignee_emp = next(
        (e for e in roster if e.email.lower() == assignee_email.lower()), None)

    step("document", f"drafting the work-assignment email for {assignee_name}")
    body = _reassign_email_body(absent, assignee_emp, prediction, router=router)
    subject = f"Covering {absent.name}'s work today"

    params = {"view": "cm", "fs": "1", "to": assignee_email, "su": subject, "body": body}
    url = "https://mail.google.com/mail/?" + urllib.parse.urlencode(params)

    step("gmail", "opening Gmail compose with the work-assignment email pre-filled")
    try:
        webbrowser.open(url)
    except Exception as exc:  # noqa: BLE001
        step("gmail", f"could not open the browser: {exc}", False)
        return DesktopResult(kind="reassign_work", executed=False, verified=False,
                             outcome="failed", mode="FAILED", steps=steps,
                             reason=str(exc))

    step("approval", "Gmail is open with the assignment email — review it and click Send",
         True)
    return DesktopResult(
        kind="reassign_work", executed=True, verified=True, outcome="complete",
        mode="GMAIL_COMPOSE", artifact_path=assignee_email,
        content_preview=(
            f"Absent: {absent.name}\nAssigned to: {assignee_name} <{assignee_email}>\n"
            f"Reason: {prediction.get('reason', '')}\n\nTo: {assignee_email}\n"
            f"Subject: {subject}\n\n{body[:200]}"),
        content_source=source,
        steps=steps,
    )
