"""ComputerAdapter interface.

A backend-neutral desktop control contract. Concrete adapters (Windows UI
Automation now; a browser adapter later) implement the same interface so the
ToolCallingController and ComputerAgent never depend on a specific backend.
All operations return structured observations/results — never raw OS handles.
"""

from __future__ import annotations

from typing import Protocol, runtime_checkable

from .models import ActionResult, DesktopObservation, ElementQuery, UIElement, WindowInfo


@runtime_checkable
class ComputerAdapter(Protocol):
    name: str

    def available(self) -> bool: ...

    # observation
    def inspect_desktop(self) -> DesktopObservation: ...
    def list_windows(self) -> list[WindowInfo]: ...
    def get_active_window(self) -> WindowInfo | None: ...

    # windows / apps (launch is allowlisted by the caller)
    def find_window(self, title: str) -> WindowInfo | None: ...
    def focus_window(self, title: str) -> ActionResult: ...
    def launch_application(self, executable: str) -> ActionResult: ...

    # elements
    def find_elements(self, query: ElementQuery) -> list[UIElement]: ...
    def inspect_element(self, query: ElementQuery) -> UIElement | None: ...

    # actions (semantic)
    def click(self, query: ElementQuery) -> ActionResult: ...
    def type_text(self, text: str, query: ElementQuery | None = None) -> ActionResult: ...
    def press_key(self, key: str) -> ActionResult: ...
    def hotkey(self, *keys: str) -> ActionResult: ...
    def wait_for(self, query: ElementQuery, *, timeout: float = 5.0) -> bool: ...
    def screenshot(self) -> str | None: ...
